BEGIN TRANSACTION;
INSERT INTO users (username,password_hash,role) VALUES ('user','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (username,password_hash,role) VALUES ('admin','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_ADMIN');
COMMIT TRANSACTION;
BEGIN TRANSACTION;
INSERT INTO events (event_name, event_begin, event_end, host_id, dj_id) VALUES ('TestParty', '01-01-2022 8pm', '01-01-2022 10pm', 1, 1);
INSERT INTO songs (title, artist) VALUES ('Hey Ya!', 'OutKast');
INSERT INTO songs (title, artist) VALUES ('Party Rock Anthem', 'LMFAO');
INSERT INTO songs (title, artist) VALUES ('1999', 'Prince');
INSERT INTO songs (title, artist) VALUES ('I Wanna Dance With Somebody', 'Whitney Houston');
INSERT INTO songs (title, artist) VALUES ('California Gurls', 'Katy Perry');
INSERT INTO songs (title, artist) VALUES ('Rehab', 'Amy Winehouse');
INSERT INTO songs (title, artist) VALUES ('Hot Girl Summer', 'Megan Thee Stallion');
INSERT INTO songs (title, artist) VALUES ('Take On Me', 'A-ha');
INSERT INTO songs (title, artist) VALUES ('I Feel It Coming', 'The Weeknd');
INSERT INTO songs (title, artist) VALUES ('Heart of Glass', 'Blondie');
INSERT INTO event_song (event_id, song_id, status) VALUES (1, 1, 'approved');
INSERT INTO event_song (event_id, song_id, status) VALUES (1, 2, 'approved');
INSERT INTO event_song (event_id, song_id, status) VALUES (1, 3, 'approved');
INSERT INTO event_song (event_id, song_id, status) VALUES (1, 4, 'approved');
INSERT INTO event_song (event_id, song_id, status) VALUES (1, 5, 'approved');
INSERT INTO event_song (event_id, song_id, status) VALUES (1, 6, 'approved');
INSERT INTO event_song (event_id, song_id, status) VALUES (1, 7, 'approved');
INSERT INTO event_song (event_id, song_id, status) VALUES (1, 8, 'approved');
INSERT INTO event_song (event_id, song_id, status) VALUES (1, 9, 'approved');
INSERT INTO event_song (event_id, song_id, status) VALUES (1, 10, 'approved');
INSERT INTO songs (title, artist) VALUES ('Gangname Style', 'Psy');
INSERT INTO songs (title, artist) VALUES ('Wind Beneath My Wings', 'Bette Midler');
INSERT INTO songs (title, artist) VALUES ('Dancing in the Dark', 'Bruce Springsteen');
INSERT INTO songs (title, artist) VALUES ('I Want It That Way', 'The Backstreet Boys');
INSERT INTO event_song (event_id, song_id, status) VALUES (1, 11, 'pending');
INSERT INTO event_song (event_id, song_id, status) VALUES (1, 12, 'pending');
INSERT INTO event_song (event_id, song_id, status) VALUES (1, 13, 'pending');
INSERT INTO event_song (event_id, song_id, status) VALUES (1, 14, 'pending');
COMMIT TRANSACTION;